_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: ""
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [58.395, 57.12, 57.375]
  BACKBONE:
    NAME: "build_retinanet_pvtv2_fpn_backbone"
  PVT:
    OUT_FEATURES: ["stage2", "stage3", "stage4"]
    EMBED_DIMS: [64, 128, 320, 512]
    NUM_HEADS: [1, 2, 5, 8]
    MLP_RATIOS: [8, 8, 4, 4]
    DEPTHS: [3, 4, 6, 3]
    SR_RATIOS: [8, 4, 2, 1]
    DROP_PATH_RATE: 0.1 
  FPN:
    IN_FEATURES: ["stage2", "stage3", "stage4"]
INPUT:
  FORMAT: "RGB"
SOLVER:
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  WARMUP_ITERS: 500 
  WARMUP_FACTOR: 0.001
  WEIGHT_DECAY: 0.0001
  BASE_LR: 0.0001
  AMP:
    ENABLED: True
TEST:
  EVAL_PERIOD: 10000
